query getPatients($sort: [String!]) {
  patients(sort: $sort) {
    data {
      id
      attributes {
        FirstName
        MiddleName
        LastName
        Birthday
        Gender
        Picture {
          data {
            attributes {
              url
              alternativeText
              formats
            }
          }
        }
        AddressLine1
        AddressLine2
        City
        Postcode
        Phone
        Email
        EmergencyContact
        EmergencyContactPhone
        
      }
    }
  }
}